export interface HabitTemplate {
  id: string;
  category: string;
  categoryIcon: string;
  icon: string;
  name: string;
  description: string;
  suggestedSize: number;
  suggestedReward: string;
  /** 채움 텀 기본 제안(FILL_CADENCE_PLAN §2, additive) — 명백한 템플릿에만 부여, 나머진 생략(=FREE). */
  recommendedCadence?: { type: 'DAILY_1' | 'DAILY_N' | 'WEEKLY_N'; n?: number };
}

export const TEMPLATE_CATEGORIES = [
  { id: 'health', name: '건강', icon: '💪' },
  { id: 'growth', name: '자기계발', icon: '📚' },
  { id: 'lifestyle', name: '생활습관', icon: '🏠' },
  { id: 'work', name: '직장/학업', icon: '💼' },
  { id: 'social', name: '관계', icon: '💝' },
  { id: 'hobby', name: '취미', icon: '🎨' },
  { id: 'mental', name: '마음건강', icon: '🧘' },
];

export const HABIT_TEMPLATES: HabitTemplate[] = [
  // ─── 건강 (8) ─────────────────────────────────────────
  {
    id: 'health-water',
    category: 'health',
    categoryIcon: '💪',
    icon: '💧',
    name: '물 마시기',
    description: '하루 8잔 물 마시기로 건강한 습관을 만들어요',
    suggestedSize: 20,
    suggestedReward: '좋아하는 음료 사먹기',
    recommendedCadence: { type: 'DAILY_N', n: 8 },
  },
  {
    id: 'health-exercise',
    category: 'health',
    categoryIcon: '💪',
    icon: '🏃',
    name: '운동하기',
    description: '매일 30분 이상 운동으로 체력을 키워요',
    suggestedSize: 20,
    suggestedReward: '운동복 새로 사기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'health-stretch',
    category: 'health',
    categoryIcon: '💪',
    icon: '🤸',
    name: '스트레칭',
    description: '아침저녁 10분 스트레칭으로 몸을 풀어요',
    suggestedSize: 15,
    suggestedReward: '마사지 받으러 가기',
    recommendedCadence: { type: 'DAILY_N', n: 2 },
  },
  {
    id: 'health-walk',
    category: 'health',
    categoryIcon: '💪',
    icon: '🚶',
    name: '걷기',
    description: '하루 만보 걷기 도전! 산책의 즐거움을 느껴요',
    suggestedSize: 30,
    suggestedReward: '새 운동화 사기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'health-sleep',
    category: 'health',
    categoryIcon: '💪',
    icon: '😴',
    name: '수면 관리',
    description: '밤 11시 전에 취침하는 규칙적인 수면 습관',
    suggestedSize: 20,
    suggestedReward: '좋은 베개 사기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'health-meditation',
    category: 'health',
    categoryIcon: '💪',
    icon: '🧘',
    name: '명상하기',
    description: '하루 10분 명상으로 마음의 평화를 찾아요',
    suggestedSize: 15,
    suggestedReward: '명상 앱 유료 구독하기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'health-vitamin',
    category: 'health',
    categoryIcon: '💪',
    icon: '💊',
    name: '비타민 챙기기',
    description: '매일 영양제를 꼬박꼬박 챙겨 먹어요',
    suggestedSize: 30,
    suggestedReward: '건강검진 예약하기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'health-weight',
    category: 'health',
    categoryIcon: '💪',
    icon: '⚖️',
    name: '체중 관리',
    description: '매일 체중을 기록하며 건강하게 관리해요',
    suggestedSize: 30,
    suggestedReward: '멋진 옷 한 벌 사기',
    recommendedCadence: { type: 'DAILY_1' },
  },

  // ─── 자기계발 (6) ─────────────────────────────────────
  {
    id: 'growth-reading',
    category: 'growth',
    categoryIcon: '📚',
    icon: '📖',
    name: '독서하기',
    description: '하루 30분 독서로 지식과 감성을 키워요',
    suggestedSize: 20,
    suggestedReward: '읽고 싶던 책 세트 구매',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'growth-study',
    category: 'growth',
    categoryIcon: '📚',
    icon: '✏️',
    name: '공부하기',
    description: '매일 꾸준히 공부하는 습관을 만들어요',
    suggestedSize: 30,
    suggestedReward: '카페에서 맛있는 거 먹기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'growth-diary',
    category: 'growth',
    categoryIcon: '📚',
    icon: '📝',
    name: '일기 쓰기',
    description: '하루를 돌아보며 일기를 작성해요',
    suggestedSize: 20,
    suggestedReward: '예쁜 다이어리 사기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'growth-english',
    category: 'growth',
    categoryIcon: '📚',
    icon: '🇬🇧',
    name: '영어 공부',
    description: '매일 영어 단어 10개 또는 문장 5개 학습하기',
    suggestedSize: 30,
    suggestedReward: '영어 원서 한 권 사기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'growth-news',
    category: 'growth',
    categoryIcon: '📚',
    icon: '📰',
    name: '뉴스 읽기',
    description: '매일 뉴스를 읽고 세상 돌아가는 일을 알아요',
    suggestedSize: 15,
    suggestedReward: '잡지 구독하기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'growth-lecture',
    category: 'growth',
    categoryIcon: '📚',
    icon: '🎓',
    name: '강의 듣기',
    description: '온라인 강의를 꾸준히 수강해요',
    suggestedSize: 20,
    suggestedReward: '원하던 강의 결제하기',
  },

  // ─── 생활습관 (6) ─────────────────────────────────────
  {
    id: 'lifestyle-wakeup',
    category: 'lifestyle',
    categoryIcon: '🏠',
    icon: '⏰',
    name: '일찍 기상',
    description: '매일 아침 같은 시간에 일어나는 습관',
    suggestedSize: 20,
    suggestedReward: '브런치 맛집 가기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'lifestyle-clean',
    category: 'lifestyle',
    categoryIcon: '🏠',
    icon: '🧹',
    name: '청소하기',
    description: '매일 10분 정리정돈으로 깨끗한 공간 만들기',
    suggestedSize: 15,
    suggestedReward: '인테리어 소품 사기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'lifestyle-cook',
    category: 'lifestyle',
    categoryIcon: '🏠',
    icon: '🍳',
    name: '요리하기',
    description: '직접 요리해서 건강한 식사를 즐겨요',
    suggestedSize: 15,
    suggestedReward: '좋은 식재료로 특별한 요리 만들기',
  },
  {
    id: 'lifestyle-saving',
    category: 'lifestyle',
    categoryIcon: '🏠',
    icon: '💰',
    name: '절약하기',
    description: '불필요한 지출을 줄이고 알뜰하게 생활해요',
    suggestedSize: 30,
    suggestedReward: '모은 돈으로 원하는 것 사기',
  },
  {
    id: 'lifestyle-organize',
    category: 'lifestyle',
    categoryIcon: '🏠',
    icon: '📦',
    name: '정리정돈',
    description: '물건을 제자리에 놓는 깔끔한 습관',
    suggestedSize: 15,
    suggestedReward: '수납용품 구매하기',
  },
  {
    id: 'lifestyle-skincare',
    category: 'lifestyle',
    categoryIcon: '🏠',
    icon: '🧴',
    name: '피부 관리',
    description: '아침저녁 꼼꼼한 스킨케어 루틴',
    suggestedSize: 20,
    suggestedReward: '좋은 화장품 사기',
    recommendedCadence: { type: 'DAILY_N', n: 2 },
  },

  // ─── 직장/학업 (5) ─────────────────────────────────────
  {
    id: 'work-morning',
    category: 'work',
    categoryIcon: '💼',
    icon: '👔',
    name: '출근 준비',
    description: '여유롭게 아침을 준비하고 출근해요',
    suggestedSize: 20,
    suggestedReward: '출퇴근 가방 사기',
  },
  {
    id: 'work-plan',
    category: 'work',
    categoryIcon: '💼',
    icon: '📋',
    name: '업무 계획',
    description: '하루 시작 전 오늘의 업무를 정리해요',
    suggestedSize: 20,
    suggestedReward: '좋은 플래너 구매하기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'work-meeting',
    category: 'work',
    categoryIcon: '💼',
    icon: '🗂️',
    name: '회의 정리',
    description: '회의 후 핵심 내용을 정리하는 습관',
    suggestedSize: 15,
    suggestedReward: '좋은 노트 사기',
  },
  {
    id: 'work-cert',
    category: 'work',
    categoryIcon: '💼',
    icon: '📜',
    name: '자격증 공부',
    description: '목표 자격증 취득을 위해 매일 공부해요',
    suggestedSize: 30,
    suggestedReward: '합격 후 축하 식사',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'work-portfolio',
    category: 'work',
    categoryIcon: '💼',
    icon: '💻',
    name: '포트폴리오',
    description: '커리어를 위한 포트폴리오를 꾸준히 만들어요',
    suggestedSize: 20,
    suggestedReward: '좋은 장비 업그레이드',
  },

  // ─── 관계 (3) ─────────────────────────────────────────
  {
    id: 'social-contact',
    category: 'social',
    categoryIcon: '💝',
    icon: '📱',
    name: '연락하기',
    description: '소중한 사람에게 먼저 연락하는 습관',
    suggestedSize: 15,
    suggestedReward: '소중한 사람과 맛있는 식사',
  },
  {
    id: 'social-compliment',
    category: 'social',
    categoryIcon: '💝',
    icon: '👍',
    name: '칭찬하기',
    description: '하루에 한 번 주변 사람을 칭찬해요',
    suggestedSize: 20,
    suggestedReward: '감사 선물 준비하기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'social-gratitude',
    category: 'social',
    categoryIcon: '💝',
    icon: '🙏',
    name: '감사하기',
    description: '감사한 일 3가지를 매일 기록해요',
    suggestedSize: 20,
    suggestedReward: '감사 편지 쓰기',
    recommendedCadence: { type: 'DAILY_1' },
  },

  // ─── 취미 (5) ─────────────────────────────────────────
  {
    id: 'hobby-drawing',
    category: 'hobby',
    categoryIcon: '🎨',
    icon: '🎨',
    name: '그림 그리기',
    description: '매일 조금씩 그림을 그리며 실력을 쌓아요',
    suggestedSize: 20,
    suggestedReward: '좋은 화구 세트 사기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'hobby-music',
    category: 'hobby',
    categoryIcon: '🎨',
    icon: '🎵',
    name: '음악 연습',
    description: '좋아하는 악기를 매일 연습해요',
    suggestedSize: 20,
    suggestedReward: '콘서트 티켓 구매',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'hobby-photo',
    category: 'hobby',
    categoryIcon: '🎨',
    icon: '📸',
    name: '사진 찍기',
    description: '일상의 아름다운 순간을 사진으로 남겨요',
    suggestedSize: 15,
    suggestedReward: '사진 인화해서 앨범 만들기',
  },
  {
    id: 'hobby-blog',
    category: 'hobby',
    categoryIcon: '🎨',
    icon: '✍️',
    name: '블로그 쓰기',
    description: '나만의 이야기를 블로그에 기록해요',
    suggestedSize: 15,
    suggestedReward: '블로그 꾸미기 템플릿 구매',
  },
  {
    id: 'hobby-coding',
    category: 'hobby',
    categoryIcon: '🎨',
    icon: '👨‍💻',
    name: '코딩하기',
    description: '매일 코드를 작성하며 개발 실력을 키워요',
    suggestedSize: 30,
    suggestedReward: '새 키보드 사기',
    recommendedCadence: { type: 'DAILY_1' },
  },

  // ─── 마음건강 (5) ─────────────────────────────────────
  {
    id: 'mental-emotion',
    category: 'mental',
    categoryIcon: '🧘',
    icon: '💭',
    name: '감정 일기',
    description: '오늘의 감정을 솔직하게 기록해요',
    suggestedSize: 20,
    suggestedReward: '좋아하는 것 하며 쉬는 날 보내기',
  },
  {
    id: 'mental-sns',
    category: 'mental',
    categoryIcon: '🧘',
    icon: '📵',
    name: 'SNS 줄이기',
    description: 'SNS 사용 시간을 하루 30분 이내로 줄여요',
    suggestedSize: 20,
    suggestedReward: 'SNS 대신 좋아하는 취미 시간',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'mental-detox',
    category: 'mental',
    categoryIcon: '🧘',
    icon: '🔌',
    name: '디지털 디톡스',
    description: '취침 1시간 전 전자기기 사용을 멈춰요',
    suggestedSize: 15,
    suggestedReward: '아날로그 취미 용품 사기',
  },
  {
    id: 'mental-affirmation',
    category: 'mental',
    categoryIcon: '🧘',
    icon: '✨',
    name: '긍정 확언',
    description: '매일 아침 나에게 긍정적인 말을 해요',
    suggestedSize: 20,
    suggestedReward: '좋아하는 향초 사기',
    recommendedCadence: { type: 'DAILY_1' },
  },
  {
    id: 'mental-alone',
    category: 'mental',
    categoryIcon: '🧘',
    icon: '🌙',
    name: '혼자만의 시간',
    description: '하루 30분 온전히 나만의 시간을 가져요',
    suggestedSize: 15,
    suggestedReward: '카페에서 여유롭게 시간 보내기',
    recommendedCadence: { type: 'DAILY_1' },
  },
];

export function getTemplatesByCategory(categoryId: string): HabitTemplate[] {
  return HABIT_TEMPLATES.filter((t) => t.category === categoryId);
}

export function getTemplateById(id: string): HabitTemplate | undefined {
  return HABIT_TEMPLATES.find((t) => t.id === id);
}
